@props(['items'])
<div x-show="invoice.open" x-cloak class="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4" @keydown.escape.window="invoice.open=false">
    <div class="glass-panel max-h-[90vh] w-full max-w-5xl overflow-y-auto rounded-3xl border border-gray-700 bg-gray-900 p-5 shadow-2xl sm:p-6">
        <div class="flex items-start justify-between gap-4 border-b border-gray-800 pb-4">
            <div class="flex gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-cyan-500/15 text-cyan-300"><i class="fa-solid fa-file-invoice text-lg"></i></span><div><h2 class="text-xl font-black">Rechnung prüfen</h2><p class="text-xs text-gray-400">Artikel prüfen, zuordnen und dem Stopp hinzufügen.</p></div></div>
            <button type="button" @click="invoice.open=false" class="rounded-xl p-2 text-gray-400 hover:bg-gray-800 hover:text-white" aria-label="Prüfung schließen"><i class="fa-solid fa-xmark text-lg"></i></button>
        </div>
        <div x-show="invoice.loading" class="py-16 text-center"><i class="fa-solid fa-spinner animate-spin text-3xl text-cyan-400"></i><p class="mt-4 font-bold">PDF wird analysiert…</p><p class="mt-1 text-xs text-gray-400" x-text="invoice.fileName"></p></div>
        <template x-if="invoice.data && !invoice.loading"><div class="space-y-4 pt-5">
            <div x-show="invoice.data.duplicate" class="rounded-xl border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-sm text-rose-300"><i class="fa-solid fa-triangle-exclamation mr-2"></i>Diese Rechnung wurde bereits verarbeitet.</div>
            <div class="grid gap-2 sm:grid-cols-3"><div class="rounded-xl border border-gray-800 bg-gray-950/40 p-3"><span class="text-[10px] font-bold uppercase text-gray-500">Rechnungsnummer</span><p class="mt-1 font-bold" x-text="invoice.data.invoice_info?.number || 'Nicht erkannt'"></p></div><div class="rounded-xl border border-gray-800 bg-gray-950/40 p-3"><span class="text-[10px] font-bold uppercase text-gray-500">Rechnungsdatum</span><p class="mt-1 font-bold" x-text="invoice.data.invoice_info?.date || 'Nicht erkannt'"></p></div><div class="rounded-xl border border-gray-800 bg-gray-950/40 p-3"><span class="text-[10px] font-bold uppercase text-gray-500">Erkannte Positionen</span><p class="mt-1 font-bold text-cyan-300" x-text="invoice.items.length"></p></div></div>
            <div class="space-y-3"><template x-for="(item, index) in invoice.items" :key="index"><article class="rounded-2xl border border-gray-800 bg-gray-950/30 p-4"><div class="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div class="min-w-0"><p class="font-black" x-text="item.invoice_bezeichnung"></p><p class="mt-1 text-xs text-gray-400"><span x-text="item.invoice_artikelnummer ? 'Art.-Nr. '+item.invoice_artikelnummer+' · ' : ''"></span><span x-text="item.invoice_einheit || 'Stück'"></span></p></div><span class="w-fit rounded-full border px-2.5 py-1 text-[11px] font-bold" :class="item.status === 'exact_match' ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300' : item.status === 'fuzzy_match' ? 'border-amber-500/30 bg-amber-500/10 text-amber-300' : 'border-rose-500/30 bg-rose-500/10 text-rose-300'" x-text="item.status === 'exact_match' ? 'Im Lager verifiziert' : item.status === 'fuzzy_match' ? 'Ähnlicher Treffer' : 'Nicht gefunden'"></span></div>
                <div class="mt-3 grid gap-2 md:grid-cols-[minmax(0,1fr)_105px_125px]"><label class="text-[10px] font-bold uppercase text-gray-500">Zuordnung<select x-model="item.item_id" class="sck-input mt-1 h-10 w-full rounded-xl text-sm normal-case"><option value="">Nicht buchen</option>@foreach($items as $warehouseItem)<option value="{{ $warehouseItem->id }}">{{ $warehouseItem->bezeichnung }}</option>@endforeach</select></label><label class="text-[10px] font-bold uppercase text-gray-500">Menge<input type="number" min="1" x-model.number="item.quantity" class="sck-input mt-1 h-10 w-full rounded-xl text-sm normal-case"></label><label class="text-[10px] font-bold uppercase text-gray-500">Netto €<input type="number" min="0" step=".01" x-model.number="item.actual_net_price" class="sck-input mt-1 h-10 w-full rounded-xl text-sm normal-case"></label></div>
                <button x-show="item.status !== 'exact_match'" type="button" @click="invoice.createIndex=index; invoice.createForm={ bezeichnung:item.invoice_bezeichnung, neue_artikelnummer:item.invoice_artikelnummer || '', einheit:item.invoice_einheit || 'Stück', steuersatz:item.invoice_ust || 19, ek_ohne_st:item.actual_net_price || 0, vk_ohne_st:item.actual_net_price || 0, artikelgruppe:'Material' }; invoice.createOpen=true" class="mt-3 text-xs font-bold text-cyan-300 hover:text-cyan-200"><i class="fa-solid fa-circle-plus mr-1"></i><span x-text="item.status === 'fuzzy_match' ? 'Als neuen Artikel anlegen' : 'Artikel anlegen'"></span></button>
            </article></template></div>
            <div class="flex flex-col-reverse gap-2 border-t border-gray-800 pt-4 sm:flex-row sm:justify-between"><button type="button" @click="invoice.open=false" class="rounded-xl border border-gray-700 px-4 py-2.5 text-sm font-bold text-gray-300 hover:bg-gray-800">Abbrechen</button><button type="button" @click="commitInvoice" :disabled="invoice.data.duplicate || !invoice.items.some(item => item.item_id)" class="rounded-xl bg-emerald-600 px-5 py-2.5 text-sm font-black text-white hover:bg-emerald-500 disabled:cursor-not-allowed disabled:opacity-40"><i class="fa-solid fa-check mr-1"></i>Bestätigen und buchen</button></div>
        </div></template>
    </div>
    <div x-show="invoice.createOpen" x-cloak class="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 p-4"><form @submit.prevent="createInvoiceItem" class="w-full max-w-lg rounded-3xl border border-gray-700 bg-gray-900 p-5 shadow-2xl"><div class="flex items-center justify-between"><div><h3 class="font-black">Artikel aus Rechnung anlegen</h3><p class="text-xs text-gray-400">Werte können vor dem Anlegen angepasst werden.</p></div><button type="button" @click="invoice.createOpen=false" class="p-2 text-gray-400"><i class="fa-solid fa-xmark"></i></button></div><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="text-xs font-bold sm:col-span-2">Bezeichnung<input required x-model="invoice.createForm.bezeichnung" class="sck-input mt-1 w-full rounded-xl"></label><label class="text-xs font-bold">Typ<select x-model="invoice.createForm.artikelgruppe" class="sck-input mt-1 w-full rounded-xl"><option>Material</option><option>Dienstleistung</option></select></label><label class="text-xs font-bold">Einheit<input x-model="invoice.createForm.einheit" class="sck-input mt-1 w-full rounded-xl"></label><label class="text-xs font-bold">Artikelnummer <span class="font-normal text-gray-500">(optional)</span><input x-model="invoice.createForm.neue_artikelnummer" maxlength="5" class="sck-input mt-1 w-full rounded-xl"></label><label class="text-xs font-bold">Steuersatz<input type="number" x-model="invoice.createForm.steuersatz" class="sck-input mt-1 w-full rounded-xl"></label><label class="text-xs font-bold">EK netto<input required type="number" min="0" step=".01" x-model="invoice.createForm.ek_ohne_st" class="sck-input mt-1 w-full rounded-xl"></label><label class="text-xs font-bold">VK netto<input required type="number" min="0" step=".01" x-model="invoice.createForm.vk_ohne_st" class="sck-input mt-1 w-full rounded-xl"></label></div><p x-show="invoice.createError" class="mt-3 text-sm text-rose-300" x-text="invoice.createError"></p><button :disabled="invoice.creating" class="mt-5 w-full rounded-xl bg-cyan-500 py-3 text-sm font-black text-gray-950 disabled:opacity-50" x-text="invoice.creating ? 'Artikel wird angelegt…' : 'Artikel anlegen und auswählen'"></button></form></div>
</div>
