@extends('sck.layouts.sck')
@section('content')
<div class="space-y-6">
    <div class="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><p class="text-xs uppercase tracking-[.25em] text-emerald-400 font-bold">SCK Sub-App</p><h1 class="text-3xl font-black">Routenplanung</h1><p class="text-gray-400">Gespeicherte Touren, Kennzahlen und Dokumentation.</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('sck.stopps.index') }}" class="px-4 py-2.5 rounded-xl border border-gray-700 font-bold">Stopps</a><a href="{{ route('sck.routen.settings') }}" class="px-4 py-2.5 rounded-xl border border-gray-700 font-bold">Einstellungen</a><a href="{{ route('sck.routen.create') }}" class="px-4 py-2.5 rounded-xl bg-emerald-600 text-white font-black">Neue Tour</a></div></div>
    <form class="glass-panel border border-gray-800 rounded-2xl p-4 grid md:grid-cols-[280px_1fr_180px_auto] gap-3"><x-sck.week-picker :value="$selectedWeek->format('o-\\WW')" accent="emerald" /><input name="search" value="{{ request('search') }}" class="sck-input rounded-xl" placeholder="Tournummer oder Titel"><select name="status" class="sck-input rounded-xl"><option value="">Alle Status</option>@foreach(['draft'=>'Entwurf','planned'=>'Geplant','in_progress'=>'Unterwegs','completed'=>'Abgeschlossen','cancelled'=>'Storniert'] as $v=>$l)<option value="{{ $v }}" @selected(request('status')===$v)>{{ $l }}</option>@endforeach</select><button class="bg-emerald-600 text-white rounded-xl px-5 font-bold">Filtern</button></form>
    <div class="flex justify-between items-center"><p class="text-sm text-gray-400">KW {{ $selectedWeek->isoWeek() }} · {{ $selectedWeek->format('d.m.') }}–{{ $selectedWeek->copy()->endOfWeek()->format('d.m.Y') }}</p><a href="{{ route('sck.wochenplanung.index', ['week' => $selectedWeek->format('o-\\WW')]) }}" class="text-sm text-orange-400">Wochenplanung öffnen →</a></div>
    <div class="grid md:grid-cols-2 xl:grid-cols-3 gap-4">@forelse($tours as $tour)<a href="{{ route('sck.routen.show',$tour) }}" class="glass-panel glass-panel-hover border border-gray-800 rounded-2xl p-5"><div class="flex justify-between gap-3"><div><span class="text-xs font-mono text-emerald-400">{{ $tour->number }}</span><h2 class="text-lg font-black mt-1">{{ $tour->title }}</h2></div><span class="text-xs uppercase font-bold text-gray-400">{{ $tour->status }}</span></div><p class="text-sm text-gray-400 mt-2">{{ optional($tour->tour_date)->format('d.m.Y') ?: 'Kein Datum' }} · {{ $tour->stops_count }} Stopps</p>@if($tour->weeklyPlan)<p class="text-xs text-orange-400 mt-1">Wochenplan: {{ $tour->weeklyPlan->name }}</p>@endif<div class="grid grid-cols-3 gap-2 mt-5 text-center"><div class="bg-gray-900/50 rounded-xl p-2"><strong>{{ number_format($tour->planned_km,1,',','.') }}</strong><small class="block text-gray-500">Plan-km</small></div><div class="bg-gray-900/50 rounded-xl p-2"><strong>{{ $tour->planned_drive_minutes }}</strong><small class="block text-gray-500">Fahrt-Min.</small></div><div class="bg-gray-900/50 rounded-xl p-2"><strong>{{ number_format($tour->travel_fee_pool,2,',','.') }} €</strong><small class="block text-gray-500">Anfahrt</small></div></div></a>@empty<div class="glass-panel border border-dashed border-gray-800 rounded-2xl p-12 text-center text-gray-400 md:col-span-2 xl:col-span-3">Für diese Woche sind keine Touren geplant.</div>@endforelse</div>{{ $tours->links() }}
</div>
@endsection
