<div class="grid md:grid-cols-2 gap-4">
    <label class="md:col-span-2 text-sm font-bold">Name *<input name="name" required value="{{ old('name', $customer?->name) }}" class="sck-input mt-1 rounded-xl w-full"></label>
    @if($customer?->datev_account)<label class="md:col-span-2 text-sm font-bold">DATEV-Konto<input readonly value="{{ $customer->datev_account }}" class="sck-input mt-1 rounded-xl w-full opacity-70 font-mono"><span class="block mt-1 text-xs font-normal text-gray-500">Wird beim erneuten DATEV-Import zur eindeutigen Zuordnung verwendet.</span></label>@endif
    <div class="md:col-span-2 relative" x-data="sckAddressSearch()" @click.outside="open=false"><label class="text-sm font-bold">Adresse suchen<input x-model="query" @input="changed" @focus="results.length&&(open=true)" class="sck-input mt-1 rounded-xl w-full" placeholder="Ab 3 Zeichen: Straße, PLZ, Ort oder gespeicherter Eintrag" autocomplete="off"></label><p class="mt-1 text-xs font-normal text-gray-500">Bis zu 3 lokale Treffer; Online-Suche nur auf Wunsch. Koordinaten entstehen erst beim Speichern.</p><div x-show="open" x-cloak class="address-results absolute z-30 left-0 right-0 mt-1 max-h-64 overflow-y-auto rounded-xl border border-gray-700 bg-gray-900 shadow-2xl"><template x-for="(item,index) in results" :key="item.source+'-'+item.id+'-'+index"><button type="button" @click="choose(item)" class="block w-full text-left px-3 py-2 hover:bg-cyan-500/10"><small class="text-cyan-400 font-bold" x-text="item.group"></small><span class="block text-sm" x-text="item.label"></span></button></template><p x-show="loading" class="p-3 text-sm text-gray-400">Suche…</p><button x-show="canSearchOnline && !loading && !searchedOnline" type="button" @click="searchOnline" class="w-full border-t border-gray-700 px-3 py-3 text-left text-sm font-bold text-cyan-400 hover:bg-cyan-500/10">Online nach „<span x-text="query"></span>“ suchen</button><p x-show="!loading&&!results.length&&searchedOnline" class="p-3 text-sm text-gray-400">Keine Treffer</p></div></div>
    <label class="text-sm font-bold">Straße<input name="street" value="{{ old('street', $customer?->street) }}" class="sck-input mt-1 rounded-xl w-full"></label>
    <label class="text-sm font-bold">Hausnummer<input name="house_number" value="{{ old('house_number', $customer?->house_number) }}" class="sck-input mt-1 rounded-xl w-full"></label>
    <label class="text-sm font-bold">PLZ<input name="postal_code" value="{{ old('postal_code', $customer?->postal_code) }}" class="sck-input mt-1 rounded-xl w-full"></label>
    <label class="text-sm font-bold">Ort<input name="city" value="{{ old('city', $customer?->city) }}" class="sck-input mt-1 rounded-xl w-full"></label>
    <input type="hidden" name="country_code" value="DE">
    <label class="text-sm font-bold">Telefon<input name="phone" value="{{ old('phone', $customer?->phone) }}" class="sck-input mt-1 rounded-xl w-full"></label>
    <label class="text-sm font-bold">E-Mail<input type="email" name="email" value="{{ old('email', $customer?->email) }}" class="sck-input mt-1 rounded-xl w-full"></label>
    <label class="text-sm font-bold">Status<select name="status" class="sck-input mt-1 rounded-xl w-full">@foreach(['active'=>'Aktiv','inactive'=>'Inaktiv','blocked'=>'Gesperrt'] as $v=>$l)<option value="{{ $v }}" @selected(old('status', $customer?->status ?? 'active')===$v)>{{ $l }}</option>@endforeach</select></label>
    <label class="text-sm font-bold">Tags<input name="tags" value="{{ old('tags', implode(', ', $customer?->tags ?? [])) }}" class="sck-input mt-1 rounded-xl w-full" placeholder="Stammkunde, Gewerbe"></label>
    <label class="md:col-span-2 text-sm font-bold">Notizen<textarea name="notes" rows="4" class="sck-input mt-1 rounded-xl w-full">{{ old('notes', $customer?->notes) }}</textarea></label>
</div>
